### ISSUE TITLE
Ridding of server-rendered user's CRUD

### ISSUE THREAD

**Issue by ClassTerr** [jasontaylordev/NorthwindTraders#179]
Hi there! Thank you for creation and maintaining this project.

I know, there is a default Microsoft template but I slightly dislike approach with default .NET Identity management interface paired with any SPA because of reloading the whole SPA after login/registration. Is there a way to have the same functionality in API + Angular, not server-rendering?
Maybe is there some further steps to implement this already planned in this project? Or maybe I understanding something wrong and this is an acceptable approach?
I will appreciate it if someone will provide a template or library for that if it exists.

**Comment by Poltergeisen** [comment]
Yeah, if there was some way to integrate OpenId Connect that would be really beneficial.

**Comment by JasonGT** [comment]
> Hi there! Thank you for creation and maintaining this project.

You're welcome - thanks for your contributions.

> I know, there is a default Microsoft template but I slightly dislike approach with default .NET Identity management interface paired with any SPA because of reloading the whole SPA after login/registration. Is there a way to have the same functionality in API + Angular, not server-rendering?
> Maybe is there some further steps to implement this already planned in this project? Or maybe I understanding something wrong and this is an acceptable approach?
> I will appreciate it if someone will provide a template or library for that if it exists.

I agree with you, I slightly dislike the approach also. I want to recreate the interface in Angular. This is straightforward to do, just time consuming. The good news is that with ASP.NET Core Identity we can scaffold the views and source code for the entire UI. This provides guidance for creating our own version. There are a few examples around, recently I came across this one; https://github.com/emonney/QuickApp/tree/master/QuickApp. It's running .NET Core 2.2 but it's quite good. In addition, this blog https://jasonwatmore.com usually has great content relating to ASP.NET Core, Angular, and Identity. 

Worth checking out. Thanks for the question.

**Comment by JasonGT** [comment]
> Yeah, if there was some way to integrate OpenId Connect that would be really beneficial.

This implementation is based on OpenId Connect. You can learn how to add new providers here; https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-3.0&tabs=visual-studio.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
