### ISSUE TITLE
[Question] "Presentation" depends on "Infrastructure" 

### ISSUE THREAD

**Issue by krispetkov** [jasontaylordev/NorthwindTraders#186]
Hi Jason,

Congrats for the great video and explanation of Clear Architecture!

One quick question though. In your video you are saying that no one should depend on the "**Infrastructure**" component. But in the "**Presentation**" project there is a dependency. The file Northwind.WebUI.Areas.Identity.Pages.Account contains a using statement that includes the "**Infrastructure**" project/dependency. 

Am i missing something? 

Thanks in advance!

**Comment by KrisPetkov** [comment]
UP @JasonGT

**Comment by pouyaSamie** [comment]
Hi 
That's exactly my question. i don't think it's right approach base on diagram and your talk

**Comment by stevieTheCoder** [comment]
I believe the dependency is taken to register the concrete implementation for dependency injection.  Note that startup.cs is the only file referencing the dependency.  This is a trade-off but provided this is the only reference it should not cause a tight coupling between layers.

**Comment by GFoley83** [comment]
Had the same question, as Presentation also depends on the Persistence project as well. While I completely understand that this is purely for DI in those projects, I'm a big fan of the "making it easy to do things right, hard to do things wrong" approach that Jason mentioned in his video.

An unsuspecting dev could inject `INotificationService` or `INorthwindDbContext` into the `WebUI` project if they created a new controller and ignored previous examples (or didn't understand them). 

Absolutely not trying to nitpick here as I love this solution, just trying to figure out if there's a nice way we could still have DI for those other projects, without having to reference them directly (e.g. load DLLs via assembly scanning ".Persistence.dll") or referencing them but preventing the interfaces from being used somehow.

**Comment by stevieTheCoder** [comment]
Not sure I follow.  The two interfaces you mention are in the application layer so the use case differs to the original question on taking unwanted dependencies on the infrastructure project? Apologies if I've misunderstood.

**Comment by GFoley83** [comment]
Sorry don't have the project in front of me at the moment but pretty sure the concrete implementations for those interfaces in the composition root of WebUI are in `Persistence` and `Infrastructure` projects, which is why they're referenced. 

My question is related to the author's in that the presentation later depends on these projects purely for DI and I be keen to hear what people might think would be a good solution to what I mentioned above.

**Comment by stevieTheCoder** [comment]
Thanks for the clarification.  You may be able to achieve this with Autofac modules and/or configuration.    I haven't explored the solution in detail but their documentation suggests being able to register types via configuration without having the presentation layer taking a dependency in the solution.  https://autofaccn.readthedocs.io/en/latest/faq/isolate-autofac.html

**Comment by danirzv** [comment]
@jasontaylordev any update about this question?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
