### ISSUE TITLE
How to use multiple DbContext

### ISSUE THREAD

**Issue by sudurrani** [jasontaylordev/NorthwindTraders#187]
Hello @JasonGT 
I need to create multiple databases each db will have it's own dbContext class so for now I have created mentioned below three classes for each db
> MainDbCcontext, MainDbContextFactory & MainDesignTimeDbContextFactoryBase
> TenantDbCcontext, TenantDbContextFactory & TenantDesignTimeDbContextFactoryBase
Each dbContext having different entities.

`Issue is when I run add-migration Init_MainDb -Context MainDbContext it creates tables for both dbContext entities`

> Similalry for 

`add-migration Init_TenantDb -Context TenantDbContext`

**Comment by brendan-ssw** [comment]
Hi, 
There are at least 2 ways for an entity type to become associated with a dbContext.
- directly putting a DbSet in the context
- configuration via model buillder.

Are you using modelBuilder.ApplyConfigurationsFromAssembly with all the configs for the different DBContexts in the one assembly?

**Comment by sudurrani** [comment]
First option.

> directly putting a DbSet in the context

**Comment by AnassL** [comment]
@sudurrani please double check the connection string names that you are using, you may have duplicated one of them in some class in the project.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
