### ISSUE TITLE
Application.Tests missing validation ?

### ISSUE THREAD

**Issue by danijel88** [jasontaylordev/NorthwindTraders#196]
Hi,
If in test related for Customer Creation I setup CustomerId as empty string test still pass, even if CustomerValidationExist. So shell you include in tests Validation or in handler better and just throw an validationexception ?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
