### ISSUE TITLE
Error: Could not load settings for 'Northwind.WebUI'

### ISSUE THREAD

**Issue by AnassL** [jasontaylordev/NorthwindTraders#201]
Hi,
I just cloned the repo including the .Net Core 3.0 version update, and after having run the app I got the following console error:
Error: Could not load settings for 'Northwind.WebUI'

![CouldNotLoadSettings](https://user-images.githubusercontent.com/15670658/67618096-5c9d6800-f7e2-11e9-854f-c380daa44f3e.jpg)

I had got the same error when I generated on VS2019 a new ASP.Net Core 3.0 Angular template and tried to change its ClientApp folder location.

I guess this is related to Identity Server configuration, but still could not figure it out. 

Any Idea ?

**Comment by nicetomytyuk** [comment]
I have the same issue, any solution for it?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
