### ISSUE TITLE
Namespace for SampleDataSeeder

### ISSUE THREAD

**Issue by vaipatel** [jasontaylordev/NorthwindTraders#203]
Hi Jason,

Thanks for your talks and starter templates.

I was looking through some of your code and found that the current namespace for the [`SampleDataSeeder`](https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Application/System/Commands/SeedSampleData/SampleDataSeeder.cs) reads `Northwind.Persistence`.

It got me wondering if `Northwind.Persistence` should be changed to `Northwind.Application.System.Commands.SeedSampleData`, similar to the namespace for the [`SeedSampleDataCommand`](https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Application/System/Commands/SeedSampleData/SeedSampleDataCommand.cs#L7), since `SampleDataSeeder` is placed in the Application layer.

Would that be more appropriate? Thanks!

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
