### ISSUE TITLE
[Question] How use multiple database?

### ISSUE THREAD

**Issue by iozcelik** [jasontaylordev/NorthwindTraders#204]
In my project, I have an in-memory, a relational and big data database. 

Some entities saved in big data, all others in relational. Specially, some relational entities also stored in memory. Besides when end-user want to keep audit, then a copy of entity goes the big data.  

I like the example. Looking simple, but I add all this cases which part of code. I am not sure.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
