### ISSUE TITLE
handler call other handler??

### ISSUE THREAD

**Issue by teamsmiley** [jasontaylordev/NorthwindTraders#205]
do you know how ?  

is this good?

i have handler Taskhandler CreateSomething() 

then i ahve to make invoice automatically after that.

so i want to call InvoiceCreateHandler in  createSomething()

any suggest?  sorry for bad english.

**Comment by majumajid** [comment]
@teamsmiley  As Mentioned in #155 ,Its not better practice.

> It's not a good practice to have queries / commands call other queries / commands. Think of the queries and commands as the high level use cases and entry points to your application. Start with the simplest approach first and if you encounter duplication follow this advice; https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/.

**Comment by GFoley83** [comment]
As majumajid mentioned, it's generally better not too.
One solution would be publish an event after you've created something and then use an event handler. 
See here:
https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Application/Customers/Commands/CreateCustomer/CreateCustomerCommand.cs#L64
https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Application/Customers/Commands/CreateCustomer/CustomerCreated.cs
https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Infrastructure/NotificationService.cs#L11

By using `await _mediator.Publish(new CustomerCreated { CustomerId = entity.CustomerId }, cancellationToken);`

You can have multiple listeners to that created event e.g. one that sends an email and another that creates an invoice.

**Comment by nixonad** [comment]
> One solution would be publish an event after you've created something and then use an event handler.
> You can have multiple listeners to that created event e.g. one that sends an email and another that creates an invoice.

I've done this successfully in my app, it's worth noting however that, if transactions are important to your scenario, depending on the configuration you use for Publish, the event handlers may or may not execute in the same transaction as the original handler. 
Also that if you do rely on transactional integrity within linked event handlers, a change to the publish strategy later will have unintended consequences.

**Comment by GFoley83** [comment]
Agree fully with your point nixonad. Application resiliency is a tricky bag. Jimmy Bogard also has an excellent series on his site covering that very topic that's a great read:

https://jimmybogard.com/refactoring-towards-resilience-a-primer/

An alternative to publishing events inside the handler could be to publish them in dedicated pipelines instead. That way transactional integrity should be maintained and you can control the orchestration - the order in which the events are dispatched.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
