### ISSUE TITLE
Silent Auth default in the template(s)?

### ISSUE THREAD

**Issue by pkali18** [jasontaylordev/NorthwindTraders#210]
I've been following this repo for some time as guidance in my development, thank you for mantaining it, it's been a huge help for me and my colleagues.
As of my understanding, the React template should be able to perform silent auth out of the box through an iframe, using redirects only as a last resort measure.
Our project, based on the React Template from .NET Core 3.0, does not seem to perform silent auth's at all. Is there any particular feature of the oidc-client that needs to be configured by hand in order for it to be able to perform those?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
