### ISSUE TITLE
Default implementation of IMapFrom.Mapping is not called when it is not implemented in the dto

### ISSUE THREAD

**Issue by keimpema** [jasontaylordev/NorthwindTraders#211]
In MappingProfile.ApplyMappingsFromAssembly:

type.GetMethod("Mapping") returns null if the dto does not implement the method

this seems to work in all cases:

var inter = type.GetInterface(typeof(IMapFrom<>).Name);
var methodInfo = inter.GetMethod("Mapping");

**Comment by Faulknerd** [comment]
I'm also seeing this issue. [Created a basic reproduction here.](https://github.com/Faulknerd/NorthwindTraders/commit/5ad1c1940e1d980594da7c21653fa6f4951e3a39)

@jasontaylordev, would you like me to create a pull request to fix? Or would your rather handle it another way?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
