### ISSUE TITLE
[Discussion] Lost with Authentication/Authorization

### ISSUE THREAD

**Issue by Pyrobolser** [jasontaylordev/NorthwindTraders#214]
I find the actual Microsoft documentation on the subject really confusing as it looks like there is a lot of different way of doing this.  
I already asked this kind of questions on the [Clean Architecture](https://github.com/JasonGT/CleanArchitecture) repository and I do not want to pollute too much but I would like to ask for the community opinion on this.  
How would you like add some kind of Admin/Users functionalities to the current application?
I am curious how this would play with the Angular 8 front-end and?

I am going to share as soon as possible my implementation of Azure AD on the Clean Architecture repository if anybody is interested into this. I am still wondering how to add some roles to this. I am also going to read into [these links](https://github.com/JasonGT/NorthwindTraders/issues/29) but I am also curious about how you guys would add this to the current project.

Thanks, I hope to start a constructive discussion, if this is polluting please just close the issue.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
