### ISSUE TITLE
[Question] Domain services of Onion architecture

### ISSUE THREAD

**Issue by CrispyDrone** [jasontaylordev/NorthwindTraders#217]
Hello,

@JasonGT
I recently watched your presentation about clean architecture and I really liked it. 

We're already working with some form of onion architecture at work but don't emply domain-driven design, and are most likely doing (a lot of) things wrong, but it's a learning process.

In the onion architecture diagram, there is a (sub)layer "Domain Services". 

![onion-architecture-diagram.png](https://user-images.githubusercontent.com/37639058/70060141-3be6e000-15e2-11ea-98ae-574918b5cabe.png)

Where would this fit in with NorthwindTraders, and what is a good approach for it? I found this issue <https://github.com/JasonGT/NorthwindTraders/issues/156> which discusses something similar, however I felt the answer evaded the question a bit.

Apologies upfront if I'm mixing up concepts, I'm still very new to all of this.

### An example: Calculating company expenses
The situation is as follows:
+ A company has multiple departments
+ A department has multiple employees
+ An employee has a salary
+ There are additional costs aside from salary
+ The application needs to calculate the wage of employees in multiple situations. For example:
  + We might want to be able to predict how wages are going to change and thus how the costs of the company might change in the near future. 
  + Accounting or HR might want to be able to check wages of individual employees at times.

To integrate this in the clean architecture, I personally see a few options:
1. Use a rich domain model:

   ```csharp
   var company = _companyRepository.GetCompany(companyId);
   var departmentCosts = company.CalculateCostsForDepartmentsOf(company);
   ```

   In here, the `CalculateCostsForDepartmentsOf` might query the company for all its `Department`s, then query for all the `Employee`s, and subsequently calculate the salary of each `Employee`:

   ```csharp
   // Department.cs
   // CalculateCosts()
   // ...
   foreach (var employee in department.Employees)
   {
   	Spending += employee.PaySalary();
   }
   // Calculate additional costs outside of employee salaries
   ```

2. Use a domain service such as `(I)CostService`:

   ```csharp
   var company = _companyRepository.GetCompany(companyId);
   var departmentCosts = _costService.CalculateCostsForDepartmentsOf(company);
   ```

  In this case, the `CostService` should be responsible for calculating the costs of employee salaries, office expenses, property costs,...

  Where would you define the interface (if even required) and the implementation? I think:
  + The interface could be defined in the domain layer
  + The implementation might be defined in the domain layer itself, the application layer, or the infrastructure layer? I guess it would all depend on what kind of dependencies it would have.

### Summary
Currently I believe the application layer is homologous to `Application Services` from the onion architecture. If we have logic that truly belongs to the domain, i.e. it is repeated in multiple places, it should be moved to the domain layer, which I think could be in the form of a rich domain, or domain services.

So, how would or should you integrate the interface and implementation of a domain service in NorthwindTraders?

### Sidenotes
Expenses calculation seems unstable to me and there are a lot of complex rules. So in reality I think it should be very flexible and for example read its rules from files.

Thanks again for the presentation and for making this excellent example repository!

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
