### ISSUE TITLE
OidcConfigurationController not a issue

### ISSUE THREAD

**Issue by PeterJD** [jasontaylordev/NorthwindTraders#218]
But a request for information on how OidcConfigurationController works in Northwind trader

any reference to articles would help, have had not much luck finding any

any other code snippets or application which use the above would help

Kind regards
Peter

**Comment by PeterJD** [comment]
Resolved this issue

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
