### ISSUE TITLE
Where should Value object be used besides domain entities?

### ISSUE THREAD

**Issue by nkw** [jasontaylordev/NorthwindTraders#219]
For example, assuming I need a value object for ProductId, which needs to be formated with some patterns with business rules. 

I will change the type of ProductId in Northwind.Domain.Entities.Product from int to ProductId (value object).

How about the Dto and Vm classes used in queries and commands: GetProductDetailQuery, GetProductsListQuery? 

How about the properties, e.g, Id of GetProductDetailQuery?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
