### ISSUE TITLE
Db Transactions

### ISSUE THREAD

**Issue by gkenaston** [jasontaylordev/NorthwindTraders#220]
First - Thank you for providing such an excellent reference!

Q: How would you make use of database transactions in a mediator handler?

**Comment by nixonad** [comment]
I considered two options for DB transactions, either implement a filter in the Asp.Net pipeline so everything within a request is in the same transaction, or implement the MediatR IPipelineBehavior and handle the transaction there.
Which is best for you depends on your solution requirements.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
