### ISSUE TITLE
ValueObject implementation does not override operators

### ISSUE THREAD

**Issue by nixonad** [jasontaylordev/NorthwindTraders#223]
Updating the ValueObject tests to use the == operator instead of explicitly calling Equals causes them to fail. I had originally thought that testing Equals was sufficient, but it's not.
I added the following to fix it:
```
    public static Boolean operator ==(ValueObject left, ValueObject right) => EqualOperator(left, right);
    public static Boolean operator !=(ValueObject left, ValueObject right) => NotEqualOperator(left, right);
```

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
