### ISSUE TITLE
Question: Application Level Dependencies

### ISSUE THREAD

**Issue by sq735** [jasontaylordev/NorthwindTraders#226]
Why does the Application layer depend on external libraries, for example: MediatR and FluentValidation. Is it Ok?

> This layer contains all application logic. It is dependent on the domain layer, but has no dependencies on any other layer or project. This layer defines interfaces that are implemented by outside layers. For example, if the application need to access a notification service, a new interface would be added to application and an implementation would be created within infrastructure.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
