### ISSUE TITLE
In my case all entities should implement an interface, but domain doesn't have access to interfaces, what should I do?

### ISSUE THREAD

**Issue by dehghani-mehdi** [jasontaylordev/NorthwindTraders#227]
Hi,

I saw your video about clean architecture, very nice job.

You mentioned all interfaces should be in Application layer and all entities in Domain layer, but I need all my entities inherit form `IEntity` interfaces, e.g:

```
public interface IEntity { } // in my case it's just marker interface
```

What should I do?

_p.s: I'm not here to discuss marker interfaces._

**Comment by hypervtechnics** [comment]
What kind of interface is it?

**Comment by dehghani-mehdi** [comment]
@hypervtechnics Just updated the first post

**Comment by hypervtechnics** [comment]
You may put those in the domain layer. Not ALL (literally) interfaces should be in application layer. Only those which represent a component/service not contained in your application layer. See here for more information: https://github.com/JasonGT/CleanArchitecture/blob/master/README.md#application

**Comment by dehghani-mehdi** [comment]
Thank you, I think having 2 places to put interfaces is not ideal solution.

**Comment by hypervtechnics** [comment]
These interfaces have different contexts, therefore two different locations are justifiable
