### ISSUE TITLE
northwind-trader-api . TS

### ISSUE THREAD

**Issue by PeterJD** [jasontaylordev/NorthwindTraders#230]
Hi
Attempted to replicate the generation of northwind-trader-api.TS without success , using
swagger studio, any advise please find attach files for study

Kind regards
Peter

[NW-Trader-API.txt](https://github.com/JasonGT/NorthwindTraders/files/4108442/NW-Trader-API.txt)
[NW-Trader-Generated.txt](https://github.com/JasonGT/NorthwindTraders/files/4108443/NW-Trader-Generated.txt)

**Comment by hannan-m** [comment]
Is there any error? What is not working?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
