### ISSUE TITLE
"SyntaxError: strict mode code may not contain 'with' statements" after updating to Angular 9

### ISSUE THREAD

**Issue by splite** [jasontaylordev/NorthwindTraders#233]
Be advice, you are going to hit the .net scaffolding bug when you update this repo to Angular 9:

```typescript
SyntaxError: strict mode code may not contain 'with' statements
```

Original issue with solution: https://github.com/angular/angular/issues/34970

Solution is to remove
```typescript
export { renderModule, renderModuleFactory } from '@angular/platform-server';
```
from `main.ts` (see link above for details)

**Comment by jasontaylordev** [comment]
Thanks, I detailed the full steps here - https://jasontaylor.dev/asp-net-core-angular-9-upgrade/.
