### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by haunguyen-groove** [jasontaylordev/NorthwindTraders#234]
How to implement asp.net core indentity to NorthwindTraders ?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
