### ISSUE TITLE
[Question] IHaveCustomMapping removed?

### ISSUE THREAD

**Issue by qazq** [jasontaylordev/NorthwindTraders#238]
IHaveCustomMapping removed?

In the branch dotnetcore22, I can use IHaveCustomMapping to create my custom mapping, but in the current branch, this file had been removed. How to create a custom mapping in the current version?

Thanks a lot.

**Comment by acesteb** [comment]
IHaveCustomMapping was removed in favor of IMapFrom with a default method.  MappingProfile.cs was also updated. To create a custom mapping, simply create a method called 'Mapping' in your class.  e.g:

```
public class SomeDto : IMapFrom<Entity> 
{
  public int Id { get; set; }
  //Other properties here

  public void Mapping(Profile profile) {
    //Define custom mappings
    profile.CreateMap<Entity, SomeDto>....
  }
} 
```

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
