### ISSUE TITLE
Separating .NET Core Web API Code and Client Code (Front end UI)

### ISSUE THREAD

**Issue by Gareth064** [jasontaylordev/NorthwindTraders#242]
In this and the solution template you have create, the .NET Core Web API code is in the same project as the Angular UI. Doesn't that make it harder to change the Front End UI, or am I missing something here?

I have it in my head that the APIs would be a layer between the Application Layer and the UI Layer. 

That way we could have multiple UI's (Web, Mobile, Desktop etc.) using the same API.

Am I thinking about this the wrong way?

**Comment by hypervtechnics** [comment]
Well you can simply exclude the ClientApp folder to a different project. You only need to take take care of the correct Api Url.
