### ISSUE TITLE
Scheduled Jobs belongs to infrastructure?

### ISSUE THREAD

**Issue by kiske1** [jasontaylordev/NorthwindTraders#243]
Hello and compliments for this application and related docs!
I'm using it as as starting point to build a windows service. I'm having an hard time to figure out where scheduled tasks belongs in the architecture layers. 
Thinking at the scheduled tasks as if they where normal user triggered operations, it seems that all the Job creation logic should be implemented in the "presentation" layer. 
But it seems that the scheduler (in my case quartz.net) is a sort of external service too, so it should go inside the infrastructure layer. 
What are your thoughts about it? 

Thanks!

**Comment by LuanMaik** [comment]
Scheduled Jobs act like a client, equals webAPI layer, so, I think it's Presentation layer

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
