### ISSUE TITLE
Failed to proxy the request 

### ISSUE THREAD

**Issue by haquevcs** [jasontaylordev/NorthwindTraders#244]
Dear Team,

Anyone helps me to understand the below error to fix.

{"error":"Failed to proxy the request to http://localhost:4200/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:4200/.\n\nThe underlying exception message was 'No connection could be made because the target machine actively refused it.'.Check the InnerException for more details."}

**Comment by haquevcs** [comment]
Any help would be highly appreciated

**Comment by jasontaylordev** [comment]
Hi @haquevcs. Be sure to check the instructions in the readme; https://github.com/jasontaylordev/NorthwindTraders#setup.

One reason you might see this error is if you didn't kick-off npm start from the ClientApp directory.

**Comment by haquevcs** [comment]
npm start - done but getting error
----------------------------------

npm : npm ERR! code ENOENT
At line:1 char:1
+ npm start
+ ~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm ERR! code ENOENT:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm ERR! syscall open
npm ERR! path D:\xxx\NorthwindTraders\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open D:\xxx\NorthwindTraders\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 



npm
 ERR! A complete log of this run can be found in:
npm ERR!
     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-04-17T07_15_55_663Z-debug.log
**Error Log**

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose stack Error: ENOENT: no such file or directory, open 'D:\xxx\NorthwindTraders\package.json'
5 verbose cwd D:\anwarul\clean Arch\NorthwindTraders
6 verbose Windows_NT 10.0.18363
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v12.16.1
9 verbose npm  v6.13.4
10 error code ENOENT
11 error syscall open
12 error path D:\xxx\NorthwindTraders\package.json
13 error errno -4058
14 error enoent ENOENT: no such file or directory, open 'D:\xxx\NorthwindTraders\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by jasontaylordev** [comment]
Run npm start from the /src/WebUI/ClientApp directory

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
