### ISSUE TITLE
Can't seem to compile Tests\WebUI.IntegrationTests

### ISSUE THREAD

**Issue by programr2b** [jasontaylordev/NorthwindTraders#245]
Can't seem to compile Tests\WebUI.IntegrationTests.

Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	WebUI.IntegrationTests	P:\proj\NorthwindTraders-master\Tests\WebUI.IntegrationTests\CSC	1	Active

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
