### ISSUE TITLE
Correct flow for complex operations

### ISSUE THREAD

**Issue by inversiondk** [jasontaylordev/NorthwindTraders#247]
Hi everybody, 
This isn't a technical issue with the code base per se but I thought this might be a good place to ask the question if others are wondering the same. 

I'm fairly new to the CQRS / Mediatr setup so please bear with me if I've missed something basic :) 
I have a flow where I need to create a customer and afterward a subscription for the customer (which requires a call to an external API). I've set up an IPaymentProvider interface to handle the external API call. 

But my question is - what is the correct way of handling this process? 
There are a few options

**Option A - The classic MVC approach**

1. CustomerController (MVC) calls Mediatr.Send(new CreateCustomerCommand(...);
2. Upon response, CustomerController (MVC) calls Mediatr.Send(new CreateSubscriptionCommand(...);
3. The CreateSubscriptionCommandHandler creates the subscription, calls the IPaymentProvider and saves changes to my system

**Option B - The Publish event approach**

1. CustomerController (MVC) calls Mediatr.Send(new CreateCustomerCommand(...);
2. CreateCustomerCommandHandler publishes a notification through Mediatr (CustomerCreated)
3. The CreateSubscriptionNotificationHandler picks up the notification, creates the subscription, calls the IPaymentProvider and saves changes to my system

**Option C - Something else entirely**

I hope my question makes sense :) 
I'm really REALLY happy with the CQRS/Mediatr set up.... I just need to get it right :) 

Thank you guys.

**Comment by MCCshreyas** [comment]
The second option is looks good from my point of view. Rather than calling two handlers from controller, you can publish the notification after creating customer and then create the subscription for that customer on other side!

And also let's say in future if you wanna create subscription for specific user then rather than adding if condition in controller (if we followed first approach) we can include the same in Create Customer handler to do same. And having business logic in handler makes more sense than having it in controller level.

**Comment by inversiondk** [comment]
Good point @MCCshreyas - thanks :) 
I think I'll explore this path a bit - unless someone feels very strongly about why this should not be the path to take.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
