### ISSUE TITLE
Error: Could not load settings for 'Northwind.WebUI'

### ISSUE THREAD

**Issue by kartalbas** [jasontaylordev/NorthwindTraders#248]
Hi everybody,

Im new in Angular and fighting with the error:

`Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:4200/_configuration/Northwind.WebUI]`

I would like to see that solution in action, just
- cloned this git repo
- dotnet build (WEBUI folder)
- dotnet run (WEBU folder)
- npm install (ClientApp folder)
- ng serve (ClientApp folder)
- open the chrome browser with http://localhost:4200/
> Error 404 as mentioned above.

I saw a [Pullrequest #224](https://github.com/jasontaylordev/NorthwindTraders/pull/224), merged them in the repo manually, but unfortuantelly didnt help.

Thanks,
Mehmet

**Comment by jasontaylordev** [comment]
Hi Mehmet. Thanks for checking out this repo.

When you launch it, you don't need to start the front end and back end separately. Just use dotnet run, and browse to https://localhost:44376. Please review the getting started steps here - https://github.com/jasontaylordev/NorthwindTraders#getting-started.

The project is an Angular + .NET Core SPA, and in development, the .NET Core back end proxies all requests to the front end. By launching 4200, you're only looking at the front end. Learn more here; https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio.

Also, recommend checking out the new Clean Architecture Solution Template; https://github.com/jasontaylordev/CleanArchitecture/. It's running the latest versions - .NET Core 3.1 and Angular 9. This is the getting started guide; https://jasontaylor.dev/clean-architecture-getting-started/.

Let me know if you run into any issues and I help out.

Happy Coding! 😃

**Comment by andrerocha** [comment]
> Hi everybody,
> 
> Im new in Angular and fighting with the error:
> 
> `Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:4200/_configuration/Northwind.WebUI]`
> 
> I would like to see that solution in action, just
> 
> * cloned this git repo
> * dotnet build (WEBUI folder)
> * dotnet run (WEBU folder)
> * npm install (ClientApp folder)
> * ng serve (ClientApp folder)
> * open the chrome browser with http://localhost:4200/
> 
> > Error 404 as mentioned above.
> 
> I saw a [Pullrequest #224](https://github.com/jasontaylordev/NorthwindTraders/pull/224), merged them in the repo manually, but unfortuantelly didnt help.
> 
> Thanks,
> Mehmet

Only run localhost5001 and not localhost:4200. You must run port that dotnet run is liten.

**Comment by jasontaylordev** [comment]
Recommend checking out https://github.com/jasontaylordev/CleanArchitecture/ instead.

It's more up to date and has better docs. Happy coding! :)
