### ISSUE TITLE
[Question] Where is used AutoMapper

### ISSUE THREAD

**Issue by danijel88** [jasontaylordev/NorthwindTraders#251]
Dear,

May I know where and how it is used AutoMapper since in Upsert and Create commands I see manually Mapping.

Regards,
Danijel

**Comment by neman** [comment]
You should **never do auto mapping** for Insert or Update. Domain model might be protected and properly encapsulated.

On the other side, get is ok and you can see the example here https://github.com/jasontaylordev/NorthwindTraders/blob/master/Src/Application/Employees/Queries/GetEmployeesList/GetEmployeesListQuery.cs

**Comment by Urgen-Dorjee** [comment]
AutoMapper works fine on flat model mapping,  however, with [this](https://github.com/jasontaylordev/NorthwindTraders/blob/28e05758d93cb838c68b91d73d8c3f28ceafe42f/Src/Application/Common/Mappings/MappingProfile.cs#L6) implementation, it has issue mapping through a constructor. When I tried to map <"Source, all the fields are initialized through the constructor (private setter),  Destination">. When I run the project it is looking for a parameterless constructor and hence all the fields are null/empty. I don't know how you can make this with constructor initialization. Thanks!

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
