### ISSUE TITLE
Why Query and QueryHandler are separated but Command and CommandHandler are merged?

### ISSUE THREAD

**Issue by dehghani-mehdi** [jasontaylordev/NorthwindTraders#259]
[DeleteCategoryCommand](https://github.com/jasontaylordev/NorthwindTraders/blob/master/Src/Application/Categories/Commands/DeleteCategory/DeleteCategoryCommand.cs)

[GetCategoriesListQuery](https://github.com/jasontaylordev/NorthwindTraders/blob/master/Src/Application/Categories/Queries/GetCategoriesList/GetCategoriesListQuery.cs)
[GetCategoriesListQueryHandler](https://github.com/jasontaylordev/NorthwindTraders/blob/master/Src/Application/Categories/Queries/GetCategoriesList/GetCategoriesListQueryHandler.cs)

**Comment by AndreiTsvettsikh** [comment]
Hi @dehghani-mehdi 
It is just a sample. So it is possible to keep request class (command/query) and handler in the same file or in separated files.
I believe better to use separate files. Just follow this easy rule: keep each class in a separate file.
And you can make handler classes as internal for better encapsulation. I mean incapsulation classes within a module.
I've created a PR so you can see it here https://github.com/jasontaylordev/NorthwindTraders/pull/254
