### ISSUE TITLE
Consistent naming for behaviors

### ISSUE THREAD

**Issue by Isitar** [jasontaylordev/NorthwindTraders#261]
The naming for the behaviors is inconsistent. 

The namespace is calles `Behaviours` and the classes are mixed (`RequestPerformanceBehaviour` and `RequestValidationBehavior`)

Since MediatR uses the us-english version, I suggest renaming it to `Behavior`

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
