### ISSUE TITLE
Do non-entities core models belong to the domain?

### ISSUE THREAD

**Issue by esetmtg** [jasontaylordev/NorthwindTraders#263]
Hello everyone.

I'm trying to adopt this architecture in one of my projects and I was wondering if the domain should only contain entities (in the database sens, that is the ones that are persisted) or if it should also contain objects that make sens business-wise. 

Say that I'm building a backend for an investment company that allow an user to see some analytics on his portfolios. I want to persist the user's portfolios, and I would create a `Domain.Entities.Portfolio` class. I'm going to need something like a `PortfolioAnalytics` object, but I'm not going to persist them in my database. In that case, should I still create a `Domain.Entities.PortfolioAnalytics`? Maybe it should go inside another domain folder, such as `Domain.Objects.PortfolioAnalytics`? Or maybe it belongs to another project, such as `Application.XXX`? I'm kind of lost. 

Regards

**Comment by AndreiTsvettsikh** [comment]
Hi @esetmtg.

Could you please provide more details - what exactly do you want from the `PortfolioAnalytics` object?
If I understand correctly? there are 2 ways:

1. Put this logic to the `Portfolio` class. Add a method and put the logic to this method.
2. Create a separate PortfolioAnalyticsService. It is a kind of Domain Services. This service can work with multiple domain objects.

Does it work for you?

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
