### ISSUE TITLE
How can we write unit test cases for controllers extending base controller as we are not using constructor injection. any leads will be appreciated.

### ISSUE THREAD

**Issue by qnxrahul** [jasontaylordev/NorthwindTraders#269]
https://stackoverflow.com/questions/62234097/unit-test-derived-controller-class-using-protected-mediator-in-base-controller-i.
I am facing the same issue  while trying to write the unit test cases

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
