### ISSUE TITLE
[Discussion] Clean Architecture - is it really?

### ISSUE THREAD

**Issue by HydraulicCamel** [jasontaylordev/NorthwindTraders#279]
Hi everybody,

First I want to thank @jasontaylordev for his great lecture and for starting this repo. 💪🏻
I am sure it helped a lot of people as it certainly helped me.
Same goes for all the devs who invested their time contributing to this project.

Now for my trollish post about what I see as a contradiction between the concept of the Clean Architecture  and its real world Implementation:

In his lecture, @jasontaylordev talks about the familiar onion drawing, representing the topography of this architecture.

The The concept of this approach is quite simple:
every layer should only consume layers that are closer to the core via abstraction/di, and (in most cases) should only reference the inner most layer - the domain/core, containing most of the abstractions and pocos (dtos, entities, models ect).

one necessary exception is the presentation layer - which is the entry point for the application. This is where the composite root is traditionally declared, which  means it has to reference all other layers (or projects) in our solution in order to register all the abstractions with their implementations.

The persistent layer (containing the data access implementation and framework) is always drawn as part of the external layer (along with the presentation and infrastructure).

This contradicts the desired 'flow' of consumption that is suggested by this architecture.
The data access in the persistent is being consumed by the inner layer - the application layer, which contains the core business logic of our application.

Things get worst when using EF.
As dbContext is almost impossible to fully abstract, it must be added/referenced within the consuming layer(s).

In the NorthwindTraders solution, INorthwindDbContext interface is used as a (semi) abstraction for dbContext.
This is a leaky abstraction as it contains DbSet - which is a part of Microsoft.EntityFrameworkCore namespace.

This means we have to add EF package into multiple layers (and project in our solution):
1) The Application project/layer (where it is consumed).
2) The WebUI project/Presentation layer (for the composite root).
3) The Persistence project/persistent layer (where dbContext is configured).

I just cant see how this approach is an improvement over the N-layer architecture as some people suggests.

What am I missing?
Any input is welcomed

**Comment by andrewtsw** [comment]
Hey @HydraulicCamel 
I believe that dependency from the EF Core does not equal dependency from the persistent layer.
The dependency rule works in this case: the application layer can not depend on the data access layer. But it depends (it uses) data access interfaces.
And there is no reference from the Application to Persistence.

But data access interface uses DbSet and depends on EF Core. Is it correct to add EF Core to the application layer?
I believe it is correct because you do not need a repository over DbSet.
The author of the "Entity Framework Core in Action" book suggests adding an EF Core to the Domain layer. I do not think that EF Core in the domain is a good idea. But EF Core in the application works great.
Because you do not use SQL server directly from your code.

What do you think about it?

**Comment by oleg-varlamov** [comment]
Hi!

I think that although there is no direct dependency, the dependency on the Data Persistence framework (EF) has "leaked" into the Application layer. If (at some stage of development) it becomes necessary to change the implementation of the repositories to use NHibernate, Dapper, or pure ADO.Net, then we will face many problems. At a minimum, the current interface assumes that the repository implementation can translate Expressions into queries to the Storage, which is not always true. Moreover, the dependency on EF clearly says that you have to use a SQL-oriented database as Storage. The current limitation will not allow me to store data in files, Redis or MongoDB, which I would like to be able to do.

Again, Jason said that it is bad practice to use EF attributes in domain entities - the framework "leaks" to the domain level. So why do we agree that the leaking framework to the Application layer is acceptable?

I believe that in this case, it is worth getting rid of the dependency on EF at the Application level.

**Comment by smarten123** [comment]
A lot of valid points have been made in this thread, but I believe Jason has chosen this approach with EF Core for the sake of simplicity. Does [this comment](https://github.com/jasontaylordev/NorthwindTraders/issues/18#issuecomment-433860061) provide enough insight?

**Comment by domicioam** [comment]
This project isn't following the Clean Architecture as described by Robert Martin. Where are the interactors? Use cases should have a slice in every layer to allow proper isolation. The entities don't contain business logic, they are POCOS. There is a strong dependency on Entity Framework and this should exist only inside the database "layer" project. I don't mean to be harsh, but if we are going to build something to be used as reference, we should at least follow what is stated in the book:

> Entities
> 
> Entities encapsulate Enterprise wide business rules. An entity can be an object with methods, or it can be a set of data structures and functions. It doesn’t matter so long as the entities could be used by many different applications in the enterprise.
> 
> If you don’t have an enterprise, and are just writing a single application, then these entities are the business objects of the application. They encapsulate the most general and high-level rules. They are the least likely to change when something external changes. For example, you would not expect these objects to be affected by a change to page navigation, or security. No operational change to any particular application should affect the entity layer.
>
> Use Cases
> 
> The software in this layer contains application specific business rules. It encapsulates and implements all of the use cases of the system. These use cases orchestrate the flow of data to and from the entities, and direct those entities to use their enterprise wide business rules to achieve the goals of the use case.
> 
> We do not expect changes in this layer to affect the entities. We also do not expect this layer to be affected by changes to externalities such as the database, the UI, or any of the common frameworks. This layer is isolated from such concerns.
> 
> We do, however, expect that changes to the operation of the application will affect the use-cases and therefore the software in this layer. If the details of a use-case change, then some code in this layer will certainly be affected.
>

> Frameworks and Drivers.
> 
> The outermost layer is generally composed of frameworks and tools such as the Database, the Web Framework, etc. Generally you don’t write much code in this layer other than glue code that communicates to the next circle inwards.
> 
> This layer is where all the details go. The Web is a detail. The database is a detail. We keep these things on the outside where they can do little harm.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
