### ISSUE TITLE
Why does it not look like shown in the XAML ControlsGallery App - DataGrid

### ISSUE THREAD

**Issue by pavll** [jasontaylordev/NorthwindTraders#281]
Why does it not look like shown in the XAML ControlsGallery App - DataGrid
Where is the nice UWP look like in the GIF from a browser tab where this program had been opened

**Comment by hypervtechnics** [comment]
Is this the correct repo?

**Comment by pavll** [comment]
I thought - did you've seen the [GIF](https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/raw/16ea181576ff06cd18b8b43d4a4394851fe2d0b7/docs/resources/images/Controls/DataGrid/DataGrid.gif)
Which is shown in the xaml controls gallery

**Comment by hypervtechnics** [comment]
I have not seen it and it does not belong to this repository I think.

Northwind (Traders) is a common name when used in hypothetical applications which are examples or showcases for some aspects. I think you are searching for a different project.

**Comment by pavll** [comment]
Ok, thank you, i'll search for it
