### ISSUE TITLE
Application layer access to DbContext?

### ISSUE THREAD

**Issue by odairto** [jasontaylordev/NorthwindTraders#293]
Hi all.
Is it correct the Hadler in Application access the DB Context in Clean Architecture aproach?

```
public async Task<ProductsListVm> Handle(GetProductsListQuery request, CancellationToken cancellationToken)
        {
                var products = await _context.Products
                .ProjectTo<ProductDto>(_mapper.ConfigurationProvider)
                .OrderBy(p => p.ProductName)
                .ToListAsync(cancellationToken)
        }
```

**Comment by LuanMaik** [comment]
He is using INorthwindDbContext to access EF implementation, so it's correct, but I prefer use repository pattern.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
