### ISSUE TITLE
A better way to do upsert

### ISSUE THREAD

**Issue by coderdnewbie** [jasontaylordev/NorthwindTraders#301]
I have recently found out a better way to do upsert. Use the update method at the Dbcontext level. See the Microsoft docs:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.update?view=efcore-6.0

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
