### ISSUE TITLE
How to call stored procedure for CURD operation?

### ISSUE THREAD

**Issue by RohillaAman** [jasontaylordev/NorthwindTraders#309]
I want to perform CURD operation using stored procedure.
can you please help me how to do it.

I m not getting the basic option for FromSQL in db context

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
