### ISSUE TITLE
This repo is pretty old and the projects don't event load in VS 2022

### ISSUE THREAD

**Issue by Tony20221** [jasontaylordev/NorthwindTraders#316]
This repo is pretty old and the projects don't even load in VS 2022. They're using .NET 2.1 and 3.0. I have wasted like 1/2 hour trying to upgrade the sdk's and target framework in the projects and this repo just doesn't compile.  These 4.9k stars must be old stars. 

I also don't know why Github's search page says this repo was last updated 3 weeks ago when the repo itself says last updated in 2020.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
