### ISSUE TITLE
FluentValidation validators execute twice, in the MVC pipeline and the MediatR pipeline

### ISSUE THREAD

**Issue by nixonad** [jasontaylordev/NorthwindTraders#76]
The FluentValidation.AspNetCore extensions add FluentValidation into the MVC pipeline as well as registering all the validators (in Startup.cs). 
We then also add the RequestValidationBehavior to MediatR which executes the validation in the MediatR pipeline. The results of the validation in the MVC pipeline get ignored since the controller action just calls Mediator.Send, but expensive validations (such as uniqueness checks against the DB) are still executed twice.
I tested this by adding a custom validator to the CreateCustomerCommandValidator which outputs a simple message to the console, then called it via the API, and the message is logged to the console twice for a single call.
```
public class CreateCustomerCommandValidator : AbstractValidator<CreateCustomerCommand>
  {
    public CreateCustomerCommandValidator() {
      RuleFor(x => x.Id).Length(5).NotEmpty();
      RuleFor(x => x.Address).MaximumLength(60);
      RuleFor(x => x.City).MaximumLength(15);
      RuleFor(x => x.CompanyName).MaximumLength(40).NotEmpty();
      this.When(p => !String.IsNullOrEmpty(p.CompanyName), () => {
        RuleFor(x => x.CompanyName).Must(BeTested);
      });
      RuleFor(x => x.ContactName).MaximumLength(30);
      RuleFor(x => x.ContactTitle).MaximumLength(30);
      RuleFor(x => x.Country).MaximumLength(15);
      RuleFor(x => x.Fax).MaximumLength(24);
      RuleFor(x => x.Phone).MaximumLength(24);
      RuleFor(x => x.PostalCode).MaximumLength(10).NotEmpty();
      RuleFor(x => x.Region).MaximumLength(15);
    }

    private Boolean BeTested(CreateCustomerCommand instanceToValidate, String customerName) {
      Console.WriteLine("Testing customerName in CreateCustomerValidator");
      return true;
    }

```
Is there a way to prevent this? Or do you have a different pattern for such cases?

**Comment by rafalschmidt97** [comment]
Try this:

```c#
services.Configure<ApiBehaviorOptions>(options => { 
  options.SuppressModelStateInvalidFilter = true; 
});
```

**Comment by nixonad** [comment]
I stopped the MVC validations from running by clearing the ModelMetadataDetailsProviders and the ModelValidatorProviders after adding FluentValidation. Feels clunky though..

```
services
          .AddMvc(options => options.Filters.Add(typeof(CustomExceptionFilterAttribute)))
          .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
          .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<CreateCustomerCommandValidator>())
          .AddMvcOptions(options => {
            options.ModelMetadataDetailsProviders.Clear();
            options.ModelValidatorProviders.Clear();
          });
```

**Comment by rafalschmidt97** [comment]
@nixonad - thanks! I'm gonna fix my project.

**Comment by nixonad** [comment]
After a little more trial and error, I removed the FluentValidation.AspNetCore package and added FluentValidation, then simply registered the validators directly in IServiceCollection using the extension methods in FV:
`services.AddValidatorsFromAssemblyContaining<CreateCustomerCommandValidator>()`

Once again feels like I'm missing something but it seems to be working.

**Comment by rafalschmidt97** [comment]
Yeah. I also don't use AspNetCore extension. Instead of that I just use this:

```c#
      // Add Validators
      services.Scan(scan =>
        scan.FromAssemblies(applicationAssembly)
          .AddClasses(classes => classes.AssignableTo(typeof(IValidator<>)))
          .AsImplementedInterfaces()
          .WithTransientLifetime());
```

**Comment by rafalschmidt97** [comment]
Hi again @nixonad,
I've found a problem with your suggestion:

with
```
options.ModelMetadataDetailsProviders.Clear();
options.ModelValidatorProviders.Clear();
```

I get always "Unsupported Media Type, status":415" for IFormFile. Do you maybe know how to solve it?

**Comment by Ilchuk-Mihail** [comment]
This approach is not very good. Because if you create some logic not in Application layer (CQRS), then you can't  use FluentValidation.
Example:
-SignIn (validate and get jwt token), 
-Forgot password (send email)
and many others_ 

Create command or queries for this will be redundant. 

I use next solution : 

I catch all validation errors and the simple pack it to my base response result in ApiBehavior

```
services.Configure<ApiBehaviorOptions>(options =>
            {
                options.InvalidModelStateResponseFactory = (context) =>
                {
                    var errors = context.ModelState.Values.SelectMany(x => x.Errors.Select(p => p.ErrorMessage)).ToList();
                    return new JsonResult(new ResponseResult(errors, "One or more validation failures have occurred."))
                    {
                        StatusCode = (int)BaseStatusCode.BadRequest,
                        ContentType = "application/json"
                    };
                };
            });
```
I don't use ValidationException  and pack it in filter, and don't use RequestValidationBehavior for run validators. 

So, validators runs only once, in controllers and I can write validators for methods above in Api layer,  and also use valitators in application layer. 

If, in future I change presentation layer. I can again include RequestValidationBehavior in pipeline. 

Thought ?

**Comment by rafalschmidt97** [comment]
@Ilchuk-Mihail it's also a cool solution! For me a validation is a part of logic so i'll still keep it inside of application layer. 

Redundant to use cqrs here? Sign in process is a part of logic of your app and you loose consistency with your approach actually. Thanks for your comment here!

**Comment by Ilchuk-Mihail** [comment]
I don't like use command/query for signIn process, user creation etc. 
I try distinguish Auth logic, Identity logic and App logic .
In my humble opinion, app layer should not know about auth logic. It's a some infrastructure/presentation part, it can changes anytime. 
For me better if, app know authorized user. "Api layer checks user token, if user have permissions -  allow use App layer logic." 

How you deal with sign in/ sign up in application layer ? 
If you use smth like UserManager - it also dependency for this layer, which in turn still have dependency on the persistence. 

Cover all app in CQRS it can be redundant, and complicated. I cover majority but not all.

**Comment by rafalschmidt97** [comment]
@Ilchuk-Mihail good explanation. Actually my app layer also doesn't know about authorization part. I've just use Context to get for example user Id from token. You're right. I'll probably refactor my code. Thanks 🚀

**Comment by nixonad** [comment]
Yeah, I wondered about side effects, that's why I switched to registering the validators with DI directly. 
I didn't encounter this since I don't use forms.

> Hi again @nixonad,
> I've found a problem with your suggestion:
> 
> with
> 
> ```
> options.ModelMetadataDetailsProviders.Clear();
> options.ModelValidatorProviders.Clear();
> ```
> I get always "Unsupported Media Type, status":415" for IFormFile.
> 
> To solve it use Request.Form.Files[0] directly instead.

**Comment by nixonad** [comment]
> This approach is not very good. Because if you create some logic not in Application layer (CQRS), then you can't use FluentValidation.

My personal approach is that if you use this architecture then you should use it everywhere. I have created separate projects for API, Application, Domain etc that concern themselves only with issues such as authentication, user management etc, but still follow the architectural pattern. Mixing and matching bits in the presentation and Application layers is going to get messy..

**Comment by rafalschmidt97** [comment]
Can you share with us how you authenticate user at CQRS level? Because for now I use built in filter in asp which check my token and fill context. Have you implemented this in Mediatr pipeline and now you can check privileges inside of request? I was thinking about something like this to have two base requests like IRequest and IAuthRequest (maybe I’ll use better name) and they will be treated differently. One of them should fill context and one not. But I was lazy so I’ve just implemented Auth with build in functionality in asp.

**Comment by nixonad** [comment]
Hi @rafalschmidt97 , sorry, I can't be of much help here. I have a SPA UI which authenticates directly with Auth0 (www.auth0.com), my api stores the tenant and user information linked to the auth0 user, but doesn't do the actual authentication.

As far as authorization goes, I have an MVC filter which extracts the claims from the JWT and injects it into a service in the DI container. Anything in the Application layer can then simply inject the service and have access to the user context info. (it is arguably better/more secure to do this using the built in identity bits in aspnetcore, but I found this to be easy and less dependant on the presentation layer)

hth

**Comment by MCCshreyas** [comment]
Has anybody found a way to avoid twice execution of validators?

cc @jasontaylordev

**Comment by nixonad** [comment]
@MCCshreyas : The solutions posted by myslef and @rafalschmidt97 above are still valid.. Don't use the FluentValidation.ASpNetCore package, just use FluentValidation, clear the ModelValidatorProviders and Scan the assemblies to add your validator classes.

**Comment by jasontaylordev** [comment]
Hi all, apologies for not being very active - I have a lot of catching up to do. If you are building new applications and want to follow the Clean Architecture approach with .NET Core 3.1 - I recommend checking out this repo - https://github.com/jasontaylordev/CleanArchitecture. 

In relation to this issue, @nixonad and @rafalschmidt97 have it right. In addition, it's worth adding a reference to FluentValidation.DependencyInjectionExtensions, as it has a handy method for wiring up all of the validators:

            `services.AddValidatorsFromAssembly(Assembly.GetExecutingAssembly());`

You can see this approach in the CleanArchitecture repo. Let me know if further clarification is required.

**Comment by MCCshreyas** [comment]
So @jasontaylordev, the issue has been fixed in template? Right?

**Comment by jasontaylordev** [comment]
> So @jasontaylordev, the issue has been fixed in template? Right?

Correct, all fixed in the template.

**Comment by MCCshreyas** [comment]
Ohh. Nice thanks. So are you going to do same fixes in this repo, sometime soon?

**Comment by jasontaylordev** [comment]
Yes for sure, I'll get it up to date in the coming weeks.

**Comment by MCCshreyas** [comment]
Yeah. Ok. Looking forward to it..
